name: first workflow
on: push
jobs:
    ASCII_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: list files
          run: |
              echo $SHELL
              echo $0  
        
        - name: execute shell script
          run: ./command.sh 
          shell: bash --noprofile --norc -exo pipefail {0}
        
       

          

        # - name: install cowsay package
        #   run: sudo apt-get install cowsay -y    
        
        # - name: generate ASCII art
        #   run: cowsay -f dragon 
             