name: first workflow
on: push
jobs:
    ASCII_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: execute shell script
          run: ./command.sh 
        
        - name: list files
          run: ls -lrta           

          

        # - name: install cowsay package
        #   run: sudo apt-get install cowsay -y    
        
        # - name: generate ASCII art
        #   run: cowsay -f dragon 
             