name: first workflow
on: push
jobs:
    ASCII_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: list files
          run: ls -lrt

        # - name: execute shell script
        #   run: |
        #      chmod +x command.sh
        #      ./command.sh  