name: docker login with Env variable

on: push

jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      run: docker build -t docker.io/docker.Username/imageName:latest

    - name: docker login
      run: docker login --username=satishkumargc --password=JEEvesh22.

    - name: docker image push
      run: docker push docker.io/docker.Username/imageName:latest

  Deploydocker:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      run: docker run -d -p 8080:80 docker.io/docker.Username/imageName:latest  