name: docker login with Env variable

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: satishkumargc
  IMAGE_NAME: github-actions-nginx

jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest


    - name: docker login
      run: echo docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: docker image push
      run: echo docker push $CONTAINER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  Deploydocker:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest 